# -*- Mode: makefile-gmake -*-

all:
%:
	@$(MAKE) -C test_base32 $*
	@$(MAKE) -C test_base64 $*
	@$(MAKE) -C test_bitset $*
	@$(MAKE) -C test_buf $*
	@$(MAKE) -C test_fmem $*
	@$(MAKE) -C test_hash $*
	@$(MAKE) -C test_itr $*
	@$(MAKE) -C test_math $*
	@$(MAKE) -C test_md $*
	@$(MAKE) -C test_mfp $*
	@$(MAKE) -C test_mpm $*
	@$(MAKE) -C test_parse $*
	@$(MAKE) -C test_ring $*
	@$(MAKE) -C test_stack $*
	@$(MAKE) -C test_str $*
	@$(MAKE) -C test_strbuf $*
	@$(MAKE) -C test_utf8 $*
	@$(MAKE) -C test_queue $*
	@$(MAKE) -C test_vector $*
