#!/bin/bash
#
# This script requires lcov to be installed
#

TESTS="\
test_base32 \
test_base64 \
test_bitset \
test_buf \
test_fmem \
test_fnull \
test_hash \
test_itr \
test_math \
test_md \
test_mfp \
test_mpm \
test_parse \
test_queue \
test_ring \
test_stack \
test_str \
test_strbuf \
test_utf8 \
test_vector"

function err() {
    echo "*** ERROR!" $1
    exit 1
}

# Check required tools
which lcov >> /dev/null || err "Please install lcov"
which dirname >> /dev/null || err "Please install dirname"
which realpath >> /dev/null || err "Please install realpath"

# LCOV 1.10 has branch coverage disabled by default
# Previous versions didn't have the --rc option
if  [ ! -z "$(lcov --help | grep ' --rc ')" ] ; then
    LCOV_OPT="--rc lcov_branch_coverage=1"
    GENHTML_OPT="--branch-coverage"
fi

COV_DIR=$(realpath "$(dirname $0)")
TEST_DIR=$(realpath "${COV_DIR}/..")
BASE_DIR=$(realpath "${TEST_DIR}/..")

SLIB_DIR="$BASE_DIR"

make -C "$BASE_DIR" clean coverage
for t in $TESTS ; do
    pushd "$TEST_DIR/$t"
    make -C "$TEST_DIR/$t" clean coverage || exit 1
    build/coverage/$t || exit 1
    popd
done

FULL_COV="$COV_DIR/full.gcov"
SLIB_COV="$COV_DIR/slib.gcov"
rm -f "$FULL_COV" "$SLIB_COV"
lcov $LCOV_OPT -c -d "$SLIB_DIR/build/coverage" -b "$SLIB_DIR" -o "$FULL_COV" || exit 1
lcov $LCOV_OPT -e "$FULL_COV" "$SLIB_DIR/src/*" -o "$SLIB_COV" || exit 1
genhtml $GENHTML_OPT "$SLIB_COV" -t "slib" --output-directory "$COV_DIR/report" || exit 1
